#!/bin/sh

sudo apt update -y 
sudo apt upgrade -y # run updates
sudo apt install -y python3 python3-pip python3-venv # install requirments

mkdir /home/$USER/meshtastic_flasher # make a directory for flasher

cd /home/$USER/meshtastic_flasher # move over to the directory

python3 -m venv venv # setup python virtual environment

source venv/bin/activate # activate python virtual environment
pip install --upgrade pip # update
pip install meshtastic-flasher # Install Flasher
